### ISSUE TITLE
bd

### ISSUE THREAD

**Issue by marcelobbfonseca** [LMafra/estudos_em_bd#1]
ola autor, no readme pra mim nao ficou claro se bd significa Bom Demais ou Becton Dickinson. #confuso
ate mais ver.

**Comment by LMafra** [comment]
Olá, indagador. BD significa Banco de dados, mas o repositório ainda está em construção. Portanto, o nome ainda está em processo de restruturação. Logo atualizaremos o readme, explicando o que será feito aqui.

Agradeço a atenção e a preocupação com o projeto. Até mais.
